movie_finder/forms/movie_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, FloatField, FileField, SubmitField


class AddMovieForm(FlaskForm):
    title = StringField("Title")
    description = TextAreaField("Description")
    duration = FloatField("Duration")
    image = FileField("Cover")
    submit = SubmitField("Add")

movie_finder/__init__.py
from flask import Flask


def create_app():
    movie_finder = Flask(__name__)
    movie_finder.config["SECRET_KEY"] = "secret"

    from movie_finder.views.main_views import main_bp
    from movie_finder.views.movie_views import movie_bp

    movie_finder.register_blueprint(main_bp)
    movie_finder.register_blueprint(movie_bp)

    return movie_finder


app = create_app()

movie_finder/views/main_views.py
from flask import Blueprint, render_template

main_bp = Blueprint("main", __name__, url_prefix="/")


@main_bp.route("/")
def index():
    return render_template("index.html")

movie_finder/views/movie_views.py
from flask import Blueprint, render_template, redirect, url_for

from movie_finder.forms.movie_forms import AddMovieForm

movie_bp = Blueprint("movie", __name__, url_prefix="/movie")


@movie_bp.route("/add", methods=["GET", "POST"])
def add_movie():
    form = AddMovieForm()

    if form.validate_on_submit():
        print(form.title.data)
        print(form.description.data)
        print(form.duration.data)

        return redirect(url_for("main.index"))


    return render_template("add_movie.html", form=form)

movie_finder/templates/add_movie.html
{% extends "base.html" %}

{% block content %}

    <form action="{{ url_for('movie.add_movie') }}" method="POST">
        <div>
            {{ form.title.label }}
            {{ form.title() }}
        </div>
        <div>
            {{ form.description.label }}
            {{ form.description() }}
        </div>
        <div>
            {{ form.duration.label }}
            {{ form.duration() }}
        </div>
        <div>
            {{ form.image.label }}
            {{ form.image() }}
        </div>
        <div>
            {{ form.submit() }}
        </div>
    </form>

{% endblock %}

movie_finder/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title%}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>

{%  block content %}

{%  endblock %}

</body>
</html>

movie_finder/templates/index.html
{%  extends "base.html" %}

{%  block title %}
    Home
{%  endblock %}

{%  block content %}
    <h1>Movie finder</h1>
{%  endblock %}